(function(){
    var c = {
        vue:{
            testPath:"https://unpkg.com/vue/dist/vue.js",
            prodPath:"https://unpkg.com/vue/dist/vue.min.js"
        },
        axios:{
            testPath:"https://unpkg.com/axios/dist/axios.js",
            prodPath:"https://unpkg.com/axios/dist/axios.min.js"
        },
        mint:{
            testJsPath:"https://unpkg.com/mint-ui/lib/index.js",
            prodJsPath:"https://unpkg.com/mint-ui/lib/index.js",
            testCssPath:"https://unpkg.com/mint-ui/lib/style.css",
            prodCssPath:"https://unpkg.com/mint-ui/lib/style.min.css"
        },
        vant:{
            testJsPath:"https://unpkg.com/vant/lib/vant.js",
            prodJsPath:"https://unpkg.com/vant/lib/vant.min.js",
            testCssPath:"https://unpkg.com/vant/lib/index.css",
            prodCssPath:"https://unpkg.com/vant/lib/index.css"
        },
        element:{
            testJsPath:"https://unpkg.com/element-ui/lib/index.js",
            prodJsPath:"https://unpkg.com/element-ui/lib/index.js",
            testCssPath:"https://unpkg.com/element-ui/lib/theme-chalk/index.css",
            prodCssPath:"https://unpkg.com/element-ui/lib/theme-chalk/index.css"
        },
        antd:{
            testJsPath:"https://unpkg.com/ant-design-vue/dist/antd.js",
            prodJsPath:"https://unpkg.com/ant-design-vue/dist/antd.min.js",
            testCssPath:"https://unpkg.com/ant-design-vue/dist/antd.css",
            prodCssPath:"https://unpkg.com/ant-design-vue/dist/antd.min.css"
        }
    }
    window.config = c;
})()